### ISSUE TITLE
crash when visiting dir with index.html

### ISSUE THREAD

**Issue by ry** [denoland/deno_net#19]
Try running 'file_server' in the deno root directory and visiting http://0.0.0.0:4500/website

```
> file_server
HTTP server listening on http://0.0.0.0:4500/
[2018-12-12 10:07:09] "GET /third_party HTTP/1.1" 200
[2018-12-12 10:07:15] "GET /third_party/v8 HTTP/1.1" 200
[2018-12-12 10:07:19] "GET /third_party/v8/README.md HTTP/1.1" 200
[2018-12-12 10:07:52] "GET /third_party/v8/AUTHORS HTTP/1.1" 200
[2018-12-12 10:08:56] "GET /third_party/v8/.gn HTTP/1.1" 200
[2018-12-12 10:09:02] "GET /build_extra HTTP/1.1" 200
TypeError: Cannot read property 'status' of undefined
    at serverLog (file:///Users/rld/.deno/deps/https/deno.land/x/net/file_server.ts:182:71)
    at http_1.listenAndServe (file:///Users/rld/.deno/deps/https/deno.land/x/net/file_server.ts:204:5)
```

**Comment by kevinkassimo** [comment]
Looks crashing from the logger... (will investigate tomorrow, too tired today...)

**Comment by bartlomieju** [comment]
My bad, I'll fix that

**Comment by ry** [comment]
Not fixed yet.

**Comment by bartlomieju** [comment]
@ry can you tell when it fails? I just tried it with #20 merged and looks ok

**Comment by zhmushan** [comment]
@ry Maybe fixed yet.
I manually cleaned up the cache.

**Comment by ry** [comment]
Ah ok when i cleaned the cache it worked. Thanks. Sorry for the noise.
